#:kivy 2.0.0
#:import utils kivy.utils
#:import MapView kivy_garden.mapview.MapView
#:import MapSource kivy_garden.mapview.MapSource
#:import ScrollView kivy.uix.scrollview
WindowManager:
    StartScreen:
        name: 'start'
        id: startscreen
    MainScreen:
        name: "main"
        id: mainscreen
    LoginScreen:
        name: 'login'
        id: loginscreen
    Notification_NoReg:
        name: 'notif_noreg'
        id: notification_noreg
    Profile_NoReg:
        name: 'profile_noreg'
        id: profile_noreg
    Lost_Filter:
        name: 'lost_filter'
        id: lost_filter
    Ad_Screen:
        name: 'ad'
        id: ad_screen
    Comment_Screen:
        name: 'comment'
        id: comment_screen
    Review_Screen:
        name: 'review'
        id: review_screen
    Service_List_Screen:
        name: 'service_list'
        id: service_list_screen
    Service_Screen:
        name: 'service'
        id: service_screen
    Service_Filter:
        name: 'service_filter'
        id: service_filter
    Profile_Screen:
        name: 'profile'
        id: profile_screen
    Personal_Data:
        name: 'data_personal'
        id: personal_data
    My_Ad_Screen:
        name: 'my_ad'
        id: my_ad_screen
    My_Service_Screen:
        name: 'my_service'
        id: my_aervice_screen
    Change_Password_Screen:
        name: 'change_password'
        id: change_password_Screen
    Add_Screen:
        name: 'add'
        id: add_screen
    Add_See_Screen:
        name: 'add_see'
        id: add_see_screen
    Add_Lost_Screen:
        name: 'add_lost'
        id: add_lost_screen
    Add_Overexposure_Screen:
        name: 'add_overexposure'
        id: add_overexposure_screen
    Add_Nanny_Screen:
        name: 'add_nanny'
        id: add_nanny_screen
    Add_Walk_Screen:
        name: 'add_walk'
        id: add_walk_screen
    Notification_Screen:
        name: 'notification'
        id: notification_screen
<RoundedButton@Button>:
    background_color: 0,0,0,0
    canvas.before:
        Color:
            rgba: (0.34,0.71,0.98,1) if self.state=='normal' else (0,.7,.7,1)  # visual feedback of press
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
<PopupMarker>:
    BoxLayout:
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: (1,1,1,1)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20]
        Image:
            id: img_marker
            source: 'Image\\logo.png'
            size_hint: 1, 1
        Label:
            id: type_marker
            color: 0,0,0,1
            font_size: '15sp'
            text: 'Пропала'
<Lost_card>:
    size_hint_y: None
    height: 200
    size_hint_x: None
    width: 500
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    canvas:
        Color:
            rgba: (0,0,0,1)
        Line:
            rectangle: self.x, self.y, self.width, self.height
    Image:
        id: card_image
        source: 'Image\\catt.jpg'
        size_hint_y: 0.9
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,0.4
        spacing: dp(25)
        pos_hint: {'center_x': .5, 'center_y': .5}
        FloatLayout:
            size_hint: 1,0.5
            Label:
                id: date
                color: 0,0,0,1
                font_size: '15sp'
                text: 'Дата/Время'
                opacity: 0
            # MDIconButton:
            #     id: btn_close
            #     icon: 'pencil'
            #     ripple_scale: 0.1
            #     user_font_size: sp(16)
            #     pos_hint: {'center_x': 0.8, 'y': 0.9}
            #     opacity: 0
            #     on_press: root.change(self)
            MDIconButton:
                id: btn_close
                icon: 'window-close'
                ripple_scale: 0.1
                user_font_size: sp(16)
                pos_hint: {'center_x': 0.9, 'y': 0.9}
                opacity: 0
                on_press: root.delete_ad(self)
        Label:
            id: card_date
            color: 0,0,0,1
            font_size: '15sp'
            text: 'Дата/Время'
        Label:
            id: gender
            color: 0,0,0,1
            font_size: '15sp'
            text: 'Мальчик'
        Label:
            id: type
            color: 0,0,0,1
            font_size: '15sp'
            text: 'Пропали'
        Label:
            id: city
            color: 0,0,0,1
            font_size: '15sp'
            text: 'Город'
<Lost_map>:
    MapView:
        id: map
        lat:55.818
        lon:37.3317
        zoom:14
        pos_hint: {'x': 0, 'y': 0}
        size_hint: 1, 1
        map_source: 'osm'
<Lost_list>:
    BoxLayout:
        orientation: "vertical"
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            bar_color: [0, 0, 0, 1]
            MDBoxLayout:
                id: container_lost
                orientation: "vertical"
                adaptive_height: True
                spacing: dp(25)

<StartScreen>:
    FloatLayout:
        RoundedButton:
            pos_hint: {'x': 0.02, 'y': 0.305}
            size_hint: 0.96, 0.05
            font_size: '20sp'   
            text: 'Войти/Зарегистрироваться'   
            on_release: 
                app.root.current = "login"
        Image:
            source: 'Image\\logo.png'
            pos_hint: {'x': 0.2, 'y': 0.4}
            size_hint: 0.6, 0.6
        Label:
            pos_hint: {'x': 0, 'y': -0.238}
            color: 0,0,0,1
            font_size: '20sp'
            text: 'или'
        RoundedButton:
            pos_hint: {'x': 0.02, 'y': 0.17}
            size_hint: 0.96, 0.05
            font_size: '20sp'
            text: 'Войти без регистрации'
            on_release:
                root.add_markers() 
                app.root.current = "main"
<MainScreen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: sp(18)
            text:'Потеряшка'
        MDIconButton:
            icon: 'filter'
            ripple_scale: 0.8
            pos_hint: {'x': 0.89, 'y': -0.2}
            user_font_size: sp(35)
            on_release:
                app.root.current = 'lost_filter'
                app.root.transition.direction = "left"
    RelativeLayout:
        size_hint: 1,0.88
        pos_hint: {'x':0,'y':0.07}
        MDTabs:
            id: tabs
            tab_hint_x: True
            allow_stretch: True
            background_color: 1,1,1,1
            text_color_normal: 0,0,0,1
            text_color_active: 0,0,0,1
            indicator_color: 0.34,0.71,0.98,1
            lock_swiping: True
            Lost_map:
                id: lost_map
                icon: 'map-marker'
                title: 'Карта'
            Lost_list:
                id: lost_list
                icon: 'format-list-bulleted'
                title: 'Список'   
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        #elevation: 20
        md_bg_color: 1,1,1,1
        canvas:
            Color:
                rgba: (0,0,0,0.5)
            Line:
                points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
        #MDFloatLayout:

        MDIconButton:
            id: nav_icon1
            icon: 'paw'
            ripple_scale: 0.8
            pos_hint: {'x': 0.05, 'y': 0.01}
            user_font_size: sp(36)
            theme_text_color: 'Custom'
            text_color: 0.34,0.71,0.98,1
            on_release:
                #app.root.transition = NoTransition()
                app.change_color(self)
                app.root.current = 'main'
        MDIconButton:
            id: nav_icon2
            icon: 'clipboard-check-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.25, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.root.current = 'service_list'
        MDIconButton:
            id: nav_icon3
            icon: 'plus-circle-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.45, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.root.current = 'add'
        MDIconButton:
            id: nav_icon4
            icon: 'bell-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.65, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.transition_notif()
        MDIconButton:
            id: nav_icon5
            icon: 'account-circle-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.84, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.transition_profile()
<Sign_in>:
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.9
        pos_hint: {'x': 0.05, 'y': 0.8}
        spacing: '10dp'
        MDTextField:
            id: email_sign
            hint_text: "Email"
            mode: "line"
        MDTextField:
            id: passw_sign
            hint_text: "Пароль"
            mode: "line"
            password: True
            password_mask: '•'
    MDIconButton:
        icon: 'eye-off'
        pos_hint: {'x': 0.9, 'y': 0.81}
        user_font_size: dp(24)
        on_release: root.ids.passw_sign.password = False if root.ids.passw_sign.password else True
        on_release: self.icon = 'eye' if root.ids.passw_sign.password else 'eye-off'
    RoundedButton:
        pos_hint: {'x': 0.02, 'y': 0.025}
        size_hint: 0.96, 0.05
        font_size: '20sp'
        color: 0,0,0,1
        text: 'Войти'
        on_release: 
            root.add_markers() 
            root.get_text_sign()
<Agreement@ButtonBehavior+Label>
<Registration>:
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.9
        pos_hint: {'center_x': 0.5, 'center_y': 0.84}
        spacing: '10dp'
        MDTextField:
            id: name_reg
            hint_text: root.hint
            mode: "line"
            set_text: root.check_text
            required: True
            helper_text_mode: "on_error"
            helper_text: "Это поле должно быть заполнено"
        MDTextField:
            id: lname_reg
            hint_text: "Фамилия"
            mode: "line"
            required: True
            helper_text_mode: "on_error"
            helper_text: "Это поле должно быть заполнено"
            set_text: root.check_text
        MDTextField:
            id: email_reg
            hint_text: "Email"
            mode: "line"
            required: True
            helper_text_mode: "on_error"
            helper_text: "Это поле должно быть заполнено"
            set_text: root.check_text
        # MDTextField:
        #     id: city_reg
        #     hint_text: "Город"
        #     mode: "line"
        #     required: True
        #     helper_text_mode: "on_error"
        #     helper_text: "Это поле должно быть заполнено"
        #     set_text: root.check_text
        MDTextField:
            id: phone_reg
            hint_text: "Мобильный телефон"
            mode: "line"
            input_filter: 'int'
            required: True
            helper_text_mode: "on_error"
            helper_text: "Это поле должно быть заполнено"
            set_text: root.check_text
        MDTextField:
            id: passw_reg1
            hint_text: "Пароль"
            mode: "line"
            password: True
            password_mask: '•'
            set_text: root.check_text
        MDTextField:
            id: passw_reg2
            hint_text: "Повторите пароль"
            mode: "line"
            password: True
            password_mask: '•'
    Label:
        id: pas_mes
        font_size: '14sp'
        color: 1,0,0,1
        text: 'Пароли не совпадают'
        pos_hint: {'center_x': 0.5, 'center_y': 0.15}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: error_name
        font_size: '11sp'
        color: 1,0,0,1
        text: 'Неккоректный ввод имени'
        pos_hint: {'center_x': 0.147, 'center_y': 0.875}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: error_lname
        font_size: '11sp'
        color: 1,0,0,1
        text: 'Неккоректный ввод фамилии'
        pos_hint: {'center_x': 0.155, 'center_y': 0.79}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: error_email
        font_size: '11sp'
        color: 1,0,0,1
        text: 'Неккоректный ввод email'
        pos_hint: {'center_x': 0.145, 'center_y': 0.7}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: error_city
        font_size: '11sp'
        color: 1,0,0,1
        text: 'Неккоректный ввод города'
        pos_hint: {'center_x': 0.15, 'center_y': 0.615}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: error_phone
        font_size: '11sp'
        color: 1,0,0,1
        text: 'Неккоректный ввод мобильного телефона'
        pos_hint: {'center_x': 0.202, 'center_y': 0.525}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: requirements_pass
        font_size: '11sp'
        color: 0,0,0,1
        text: 'Пароль должен содержать хотя бы одно число,\nхотя бы одну латинскую букву в нижнем и верхнем регистре,\nможет содержать @#$%-_.\nДлина составляет от 6 до 20 символов'
        pos_hint: {'center_x': 0.34, 'center_y': 0.32}
        disabled: False
    MDIconButton:
        icon: 'eye-off'
        pos_hint: {'x': 0.9, 'y': 0.448}
        user_font_size: dp(24)
        on_release: root.ids.passw_reg1.password = False if root.ids.passw_reg1.password else True
        on_release: self.icon = 'eye' if root.ids.passw_reg1.password else 'eye-off'
    MDIconButton:
        icon: 'eye-off'
        pos_hint: {'x': 0.9, 'y': 0.36}
        user_font_size: dp(24)
        on_release: root.ids.passw_reg2.password = False if root.ids.passw_reg2.password else True
        on_release: self.icon = 'eye' if root.ids.passw_reg2.password else 'eye-off'
    RoundedButton:
        id: btn_reg
        pos_hint: {'x': 0.02, 'y': 0.05}
        size_hint: 0.96, 0.05
        font_size: '20sp'
        color: 0,0,0,1
        text: 'Зарегистрироваться'
        on_release:
            root.add_markers()  
            root.check_field()
    Agreement:
        pos_hint: {'center_x': 0.5, 'center_y': 0.02}
        size_hint_y: 0.01
        font_size: '12sp'
        color: 0.22,0.42,1,1
        markup: True
        text:'Нажимая на кнопку "Зарегистрироваться" вы даёте согласие на [u]обработку персоналльных данных[/u]'
        on_press:
            import webbrowser
            webbrowser.open('https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/i/UvunXBkVPxGAJA')
<LoginScreen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Вход/Регистрация'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "start"
                app.root.transition.direction = "right"
    FloatLayout:
        size_hint: 1,0.95
        MDTabs:
            tab_hint_x: True
            allow_stretch: True
            tab_indicator_type: 'line'
            tab_indicator_anim: True
            background_color: 1,1,1,1
            text_color_normal: 0,0,0,1
            text_color_active: 0,0,0,1
            indicator_color: 0.34,0.71,0.98,1
            lock_swiping: True
            Sign_in:
                icon: 'account-key'
                title: 'Войти'
            Registration:
                icon: 'account-plus'
                title: 'Зарегистрироваться'
<Notification_NoReg>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Уведомления'
    BoxLayout:
        orientation: 'vertical'
        size_hint: 0.7,0.2
        pos_hint: {'x':0.16,'y':0.42}
        spacing: 10
        Label:
            color: 0,0,0,1
            font_size: '25sp'
            text:'Для просмотра уведомлений,\n необходимо войти в аккаунт'
        RoundedButton:
            font_size: '25sp'
            text: 'Войти'
            on_release: 
                app.root.current = "login"
                app.root.transition.direction = "right"
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        #elevation: 20
        md_bg_color: 1,1,1,1
        MDFloatLayout:
            canvas:
                Color:
                    rgba: (0,0,0,0.5)
                Line:
                    points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
            size_hint_x: 1
            pos_hint: {'x': 0, 'y': 0}
            MDIconButton:
                id: nav_icon1
                icon: 'paw'
                ripple_scale: 0.8
                pos_hint: {'x': 0.05, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0.34,0.71,0.98,1
                on_release:
                    #app.root.transition = NoTransition()
                    app.change_color(self)
                    app.root.current = 'main'
                    app.root.transition.direction = "right"
            MDIconButton:
                id: nav_icon2
                icon: 'clipboard-check-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.25, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'service_list'
                    app.root.transition.direction = "right"
            MDIconButton:
                id: nav_icon3
                icon: 'plus-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.45, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'add'
            MDIconButton:
                id: nav_icon4
                icon: 'bell-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.65, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.transition_notif()
            MDIconButton:
                id: nav_icon5
                icon: 'account-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.84, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.transition.direction = "left"
                    app.transition_profile()
<Profile_NoReg>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Уведомления'
    BoxLayout:
        orientation: 'vertical'
        size_hint: 0.7,0.2
        pos_hint: {'x':0.16,'y':0.42}
        spacing: 10
        Label:
            color: 0,0,0,1
            font_size: '25sp'
            text_size: self.size
            halign: 'center'
            valign: 'middle'
            text:'Для просмотра профиля,\nнеобходимо войти в аккаунт'
        RoundedButton:
            font_size: '25sp'
            text: 'Войти'
            on_release: 
                app.root.current = "login"
                app.root.transition.direction = "right"
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        #elevation: 20
        md_bg_color: 1,1,1,1
        MDFloatLayout:
            canvas:
                Color:
                    rgba: (0,0,0,0.5)
                Line:
                    points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
            size_hint_x: 1
            pos_hint: {'x': 0, 'y': 0}
            MDIconButton:
                id: nav_icon1
                icon: 'paw'
                ripple_scale: 0.8
                pos_hint: {'x': 0.05, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0.34,0.71,0.98,1
                on_release:
                    #app.root.transition = NoTransition()
                    app.change_color(self)
                    app.root.current = 'main'
                    app.root.transition.direction = "right"
            MDIconButton:
                id: nav_icon2
                icon: 'clipboard-check-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.25, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'service_list'
                    app.root.transition.direction = "right"
            MDIconButton:
                id: nav_icon3
                icon: 'plus-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.45, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'add'
            MDIconButton:
                id: nav_icon4
                icon: 'bell-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.65, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.transition.direction = "right"
                    app.transition_notif()
            MDIconButton:
                id: nav_icon5
                icon: 'account-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.84, 'y': -0.1}
                user_font_size: dp(48)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.transition_profile()
<Lost_Filter>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Фильтры'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "main"
                app.root.transition.direction = "right"
    FloatLayout:
        orientation: 'vertical'
        size_hint: 0.8,0.8
        pos_hint: {'center_x': .4, 'center_y': .45}
        MDLabel:
            color: 0,0,0,1
            font_size: '20sp'
            text:'Тип'
            pos_hint: {'x': 0.09, 'y': 0.52}
        CheckBox:
            id: type_cb_lost
            size_hint: None, None
            size: dp(60), dp(60)
            pos_hint: {'x': 0.05, 'y': 0.9}
            color: 0,0,0,1
        MDLabel:
            color: 0,0,0,1
            font_size: '18sp'
            text:'Пропали'
            pos_hint: {'x': 0.22, 'y': 0.447}
        CheckBox:
            id: type_cb_detect
            size_hint: None, None
            size: dp(60), dp(60)
            pos_hint: {'x': 0.05, 'y': 0.85}
            color: 0,0,0,1
        MDLabel:
            color: 0,0,0,1
            font_size: '18sp'
            text:'Замечены'
            pos_hint: {'x': 0.22, 'y': 0.397}
        MDTextField:
            id: city
            hint_text: 'Город'
            mode: 'line'
            pos_hint: {'x': 0.114, 'y': 0.75}
        MDLabel:
            color: 0,0,0,1
            font_size: '20sp'
            text:'Вид'
            pos_hint: {'x': 0.09, 'y': 0.2}
        CheckBox:
            id: kind_cb_cat
            size_hint: None, None
            size: dp(60), dp(60)
            pos_hint: {'x': 0.05, 'y': 0.58}
            color: 0,0,0,1
        MDLabel:
            color: 0,0,0,1
            font_size: '18sp'
            text:'Кошка'
            pos_hint: {'x': 0.22, 'y': 0.125}
        CheckBox:
            id: kind_cb_dog
            size_hint: None, None
            size: dp(60), dp(60)
            pos_hint: {'x': 0.05, 'y': 0.53}
            color: 0,0,0,1
        MDLabel:
            color: 0,0,0,1
            font_size: '18sp'
            text:'Собака'
            pos_hint: {'x': 0.22, 'y': 0.075}
        MDLabel:
            color: 0,0,0,1
            font_size: '20sp'
            text:'Пол'
            pos_hint: {'x': 0.09, 'y': 0}
        CheckBox:
            id: gender_cb_man
            size_hint: None, None
            size: dp(60), dp(60)
            pos_hint: {'x': 0.05, 'y': 0.38}
            color: 0,0,0,1
        MDLabel:
            color: 0,0,0,1
            font_size: '18sp'
            text:'Мальчик'
            pos_hint: {'x': 0.22, 'y': -0.075}
        CheckBox:
            id: gender_cb_wom
            size_hint: None, None
            size: dp(60), dp(60)
            pos_hint: {'x': 0.05, 'y': 0.33}
            color: 0,0,0,1
        MDLabel:
            color: 0,0,0,1
            font_size: '18sp'
            text:'Девочка'
            pos_hint: {'x': 0.22, 'y': -0.125}
    RoundedButton:
        pos_hint: {'x': 0.02, 'y': 0.025}
        size_hint: 0.96, 0.05
        font_size: '20sp'
        color: 0,0,0,1
        text: 'Применить'
        on_release: root.apply_filter()
    RoundedButton:
        id: btn_reset
        pos_hint: {'x': 0.02, 'y': 0.1}
        size_hint: 0.96, 0.05
        font_size: '20sp'
        color: 0,0,0,1
        text: 'Сбросить'
        on_release: root.reset_filter()
        opacity: 0
        disabled: True  
            #app.root.current = "start"
            #app.root.transition.direction = "right"
<Ad>:
    Image:
        id: ad_image
        source: 'Image\\cat.png'
        size_hint: 0.6, None
        height: 150
        pos_hint: {'x':0.2,'y':0.85}
    Label:
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Видели тут'
        size_hint: None, None
        pos_hint: {'x':0.05,'y':0.77}
    Label:
        id: ad_date
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Дата'
        size_hint: None, None
        pos_hint: {'center_x': 0.1, 'center_y': 0.9}
        disabled: True
    MapView:
        id: ad_map
        lat:55.818
        lon:37.3317
        zoom:15
        pos_hint: {'x': 0.1, 'y': 0.48}
        size_hint: 0.8, None
        height: 300
        map_source: "osm"
        MapMarkerPopup:
            id: ad_mapmarker
            source: 'Image\\marker.png'
    Image:
        source: 'Image\\pet.png'
        size_hint: None, None
        height: 32
        width: 32
        pos_hint: {'x': 0.05, 'y':0.4}
    Label:
        id: ad_kind
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Собака'
        size_hint: None, None
        pos_hint: {'x':0.1,'y':0.365}
    Image:
        source: 'Image\\gender.png'
        size_hint: None, None
        height: 32
        width: 32
        pos_hint: {'x': 0.05, 'y':0.35}
    Label:
        id: ad_gender
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Мальчик'
        size_hint: None, None
        pos_hint: {'x':0.11,'y':0.315}
    Label:
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Комментарий:'
        size_hint: None, None
        pos_hint: {'x':0.06,'y':0.27}
    Label:
        id: ad_text
        color: 0,0,0,1
        font_size: '15sp'
        size_hint: 0.9, None
        pos_hint: {'x':0.05,'y':0.17}
        text_size: self.width, None
        text:'Доброго времени суток. Помогите пожалуйста найти домашнего питомца. Был утерян в Белоозёрском Воскресенский район. В районе церкви. Убежал. Кобель американского стафордширского терьера. Зовут Дин. Ошейник красного цвета и адресник с номером телефона хозяина.Пожалуйста кто-то что-то видел или слышал сообщите.Будем благодарны за любую информацию'
    Label:
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Контактные данные'
        size_hint: None, None
        pos_hint: {'center_x':0.5,'y':0.08}
    Label:
        id: ad_name
        color: 0,0,0,1
        font_size: '17sp'
        text: root.name
        size_hint: None, None
        pos_hint: {'x':0.32,'y':0.05}
    Label:
        id: ad_phone
        color: 0,0,0,1
        font_size: '17sp'
        text: 'Телефон'
        size_hint: None, None
        pos_hint: {'x':0.52,'y':0.05}
    MDFillRoundFlatIconButton:
        id: btn_com
        icon: "comment-outline"
        text: "Открыть комментарии"
        theme_text_color: "Custom"
        text_color: 1, 1, 1, 1
        theme_icon_color: "Custom"
        icon_color: 1, 1, 1, 1
        md_bg_color: 0.34,0.71,0.98,1
        font_size: '17sp'
        user_font_size: dp(36)
        pos_hint: {'center_x':0.5,'y':0.03}
        on_press:
            app.root.current = 'comment'
    RoundedButton:
        id: btn_change
        pos_hint: {'center_x': 0.5, 'center_y': 0.01}
        size_hint: 0.96, 0.02
        font_size: '20sp'
        color: 0,0,0,1
        text: 'Добавить'
        opacity: 0
        on_press:
            root.change()
<Comment_card>:
    size_hint_y: None
    height: 100
    size_hint_x: None
    width: 500
    orientation: 'vertical'
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    FloatLayout:
        size_hint: 1,1
        Label:
            id: user
            color: 0,0,0,1
            font_size: '15sp'
            pos_hint: {'center_x': 0.9, 'center_y': 0.9}
            text: 'Мария'
        Label:
            id: text_card
            color: 0,0,0,1
            font_size: '15sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            text: 'Мария'
        Label:
            id: date_card
            color: 0,0,0,1
            font_size: '15sp'
            pos_hint: {'center_x': 0.6, 'center_y': 0.9}
            text: 'Мария'
<Comment_Screen>:
    on_enter: root.download_data()
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Комментарии'
        Label:
            id: count_card
            pos_hint: {'x':0.3,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'0'
            opacity: 0
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "ad"
                app.root.transition.direction = "right"
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1, 0.95
        pos_hint: {'center_x': 0.5, 'y': 0}
        ScrollView:
            id: sv
            do_scroll_x: False
            bar_color: [0, 0, 0, 1]
            size_hint: 1, 0.95
            FloatLayout:
                id: scroll
                size_hint_y: None
                height: 700
    FloatLayout:
        size_hint: 1, 0.05
        pos_hint: {'center_x': 0.5, 'y': 0}
        MDTextFieldRect:
            id: text_comment
            multiline: True
            size_hint: 0.85, 0.8
            pos_hint: {'center_x': 0.45, 'center_y': 0.5}
        MDIconButton:
            id: btn
            icon: 'arrow-right'
            icon_size: dp(22)
            pos_hint: {'center_x': 0.95, 'center_y': 0.5}
            md_bg_color: 0.34,0.71,0.98,1
            on_press: root.send_comment()
<Reviews_card>:
    size_hint_y: None
    height: 100
    size_hint_x: None
    width: 500
    orientation: 'vertical'
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    Label:
        id: user
        color: 0,0,0,1
        font_size: '15sp'
        size_hint: 1, 0.5
        text_size: self.width, self.height
        halign: 'right'
        valign: 'top'
        text: 'Мария'
    Label:
        id: text_card
        color: 0,0,0,1
        font_size: '15sp'
        size_hint: 1, None
        text_size: self.width, None
        halign: 'center'
        text: 'Доброго времени суток. Помогите пожалуйста найти домашнего питомца.'
    Label:
        id: date_card
        color: 0,0,0,1
        font_size: '15sp'
        size_hint: 1, None
        text_size: self.width, None
        halign: 'center'
<Review_Screen>:
    on_enter: root.download_data()
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Отзывы'
        Label:
            id: count_card
            pos_hint: {'x':0.3,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'0'
            opacity: 0
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "service"
                app.root.transition.direction = "right"
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1, 0.94
        pos_hint: {'center_x': 0.5, 'y': 0}
        ScrollView:
            id: sv
            do_scroll_x: False
            bar_color: [0, 0, 0, 1]
            size_hint: 1, 0.94
            FloatLayout:
                id: scroll
                size_hint_y: None
                height: 700
    FloatLayout:
        size_hint: 1, 0.05
        pos_hint: {'center_x': 0.5, 'y': 0}
        MDTextFieldRect:
            id: text_review
            multiline: True
            size_hint: 0.85, 0.8
            pos_hint: {'center_x': 0.45, 'center_y': 0.5}
        MDIconButton:
            id: btn
            icon: 'arrow-right'
            icon_size: dp(22)
            pos_hint: {'center_x': 0.95, 'center_y': 0.5}
            md_bg_color: 0.34,0.71,0.98,1
            on_press: root.send_review()
            
<Ad_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Потеряшка'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "main"
                app.root.transition.direction = "right"
        MDIconButton:
            icon: 'star-outline'
            pos_hint: {'center_x': 0.96, 'center_y': 0.5}
            user_font_size: dp(24)
            #on_release:
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        Ad:
            id: ad_container
            size_hint_y: None
            height: 1000
            

<Service_card>:
    orientation: 'vertical'
    size_hint_y: None
    height: 200
    size_hint_x: None
    width: 500
    pos_hint: {'center_x': .5, 'center_y': .5}
    canvas:
        Color:
            rgba: (0,0,0,1)
        Line:
            rectangle: self.x, self.y, self.width, self.height
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.5
        Image:
            id: card_image
            size_hint: 0.8,0.8
            pos_hint: {'center_x': .5, 'center_y': .5}
            source: 'Image\\service_card.png'
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,0.9
            pos_hint: {'center_x': .2, 'center_y': .37}
            spacing: dp(10)
            FloatLayout:
                size_hint: 1,0.1
                Label:
                    id: date
                    color: 0,0,0,1
                    font_size: '15sp'
                    pos_hint: {'center_x': 0.1, 'y': 0}
                    text: 'Дата'
                    opacity: 0
                MDIconButton:
                    id: btn_close
                    icon: 'window-close'
                    ripple_scale: 0.1
                    user_font_size: sp(15)
                    pos_hint: {'center_x': 0.9, 'y': 0}
                    opacity: 0
                    on_press: root.delete_service(self)
            Label:
                id: name_service_card
                color: 0,0,0,1
                text_size: self.size
                halign: 'left'
                font_size: '15sp'
                text: 'Name'
            Label:
                id: city_service_card
                color: 0,0,0,1
                text_size: self.size
                halign: 'left'
                font_size: '15sp'
                text: 'Город'
            Label:
                id: kind_service_card
                color: 0,0,0,1
                font_size: '15sp'
                text_size: self.size
                halign: 'left'
                text: 'Вид услуги'
                disabled: False
            Label:
                id: date_service_card 
                color: 0,0,0,1
                font_size: '15sp'
                text: 'Дата'
                disabled: True
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,0.2
        pos_hint: {'center_x': .5, 'center_y': .5}
        canvas:
            Color:
                rgba: (0,0,0,0.4)
            Line:
                points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
        Label:
            id: price_service_card
            color: 0,0,0,1
            text_size: self.size
            valign: "middle"
            padding_x: 23
            font_size: '15sp'
            text: 'Стоимость'
<Service_Filter>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Фильтры'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "service_list"
                app.root.transition.direction = "right"
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2000
            MDTextField:
                id: city
                hint_text: 'Город'
                mode: 'line'
                size_hint_x: 0.7
                pos_hint: {'center_x': 0.4, 'center_y': 0.98}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Вид услуги'
                pos_hint: {'center_x': 0.16, 'center_y': 0.93}
            CheckBox:
                id: kind_cb_overexposure
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.88}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Передержка'
                pos_hint: {'center_x': 0.25, 'center_y': 0.88}
            CheckBox:
                id: kind_cb_nanny
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.83}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Няня'
                pos_hint: {'center_x': 0.2, 'center_y': 0.83}
            CheckBox:
                id: kind_cb_walk
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.78}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Выгул'
                pos_hint: {'center_x': 0.2, 'center_y': 0.78}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Вид животного'
                pos_hint: {'center_x': 0.18, 'center_y': 0.73}
            CheckBox:
                id: kind_pet_cat
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.68}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Кошка'
                pos_hint: {'center_x': 0.2, 'center_y': 0.68}
            CheckBox:
                id: kind_pet_dog
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.63}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Собака'
                pos_hint: {'center_x': 0.2, 'center_y': 0.63}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Размер собаки'
                pos_hint: {'center_x': 0.18, 'center_y': 0.58}
            CheckBox:
                id: small_size
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.53}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Маленькие породы собак (до 12 кг и до 28 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.53}
            CheckBox:
                id: medium_size
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.48}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Средние породы собак (12-25 кг, 28-60 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.48}
            CheckBox:
                id: large_size
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.43}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Крупные породы собак (от 25 кг, от 60 см рост)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.43}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Возраст'
                pos_hint: {'center_x': 0.12, 'center_y': 0.38}
            CheckBox:
                id: age_up_1
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.36}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'До 1 года'
                pos_hint: {'center_x': 0.3, 'center_y': 0.36}
            CheckBox:
                id: age_from_1
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.31}
                color: 0,0,0,1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Старше 1 года'
                pos_hint: {'center_x': 0.3, 'center_y': 0.31}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Стоимость'
                pos_hint: {'center_x': 0.12, 'center_y': 0.25}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'от'
                pos_hint: {'center_x': 0.1, 'center_y': 0.23}
            MDTextFieldRect:
                id: from_price
                size_hint: 0.2, None
                height: dp(30)
                pos_hint: {'center_x': 0.3, 'center_y': 0.23}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'до'
                pos_hint: {'center_x': 0.5, 'center_y': 0.23}
            MDTextFieldRect:
                id: to_price
                size_hint: 0.2, None
                height: dp(30)
                pos_hint: {'center_x': 0.8, 'center_y': 0.23}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Специальные возможности'
                pos_hint: {'center_x': 0.3, 'center_y': 0.15}
            MDSwitch:
                id: give_medicine
                pos_hint: {'center_x': 0.1, 'center_y': 0.11}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Давать лекарства'
                pos_hint: {'center_x': 0.5, 'center_y': 0.11}
            MDSwitch:
                id: do_injection
                pos_hint: {'center_x': 0.1, 'center_y': 0.09}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Делать уколы'
                pos_hint: {'center_x': 0.5, 'center_y': 0.09}
            MDSwitch:
                id: control
                pos_hint: {'center_x': 0.1, 'center_y': 0.07}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Круглосуточный контроль'
                pos_hint: {'center_x': 0.5, 'center_y': 0.07}
            MDSwitch:
                id: education
                pos_hint: {'center_x': 0.1, 'center_y': 0.05}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Профильное образование'
                pos_hint: {'center_x': 0.5, 'center_y': 0.05}
            RoundedButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.02}
                size_hint: 0.96, 0.02
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Применить'
                on_release: root.apply_filter()
            RoundedButton:
                id: btn_reset
                pos_hint: {'x': 0.02, 'y': 0.1}
                size_hint: 0.96, 0.05
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Сбросить'
                on_release: root.reset_filter()
                opacity: 0
                disabled: True 
<Service_List_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Услуги'
        MDIconButton:
            icon: 'filter'
            ripple_scale: 0.8
            pos_hint: {'x': 0.93, 'y': -0.2}
            user_font_size: sp(35)
            on_release:
                app.root.current = 'service_filter'
                app.root.transition.direction = "left"
    BoxLayout:
        orientation: "vertical"
        size_hint: 1,0.88
        pos_hint: {'x': 0, 'y': 0.07}

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            bar_color: [0, 0, 0, 1]
            MDBoxLayout:
                id: container_service
                orientation: "vertical"
                adaptive_height: True
                spacing: dp(25)
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        md_bg_color: 1,1,1,1
        MDFloatLayout:
            canvas:
                Color:
                    rgba: (0,0,0,0.5)
                Line:
                    points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
            size_hint_x: 1
            pos_hint: {'x': 0, 'y': 0}
            MDIconButton:
                id: nav_icon1
                icon: 'paw'
                ripple_scale: 0.8
                pos_hint: {'x': 0.05, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0.34,0.71,0.98,1
                on_release:
                    #app.root.transition = NoTransition()
                    app.change_color(self)
                    app.root.transition.direction = "right"
                    app.root.current = 'main'
            MDIconButton:
                id: nav_icon2
                icon: 'clipboard-check-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.25, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'service_list'
            MDIconButton:
                id: nav_icon3
                icon: 'plus-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.45, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'add'
            MDIconButton:
                id: nav_icon4
                icon: 'bell-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.65, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.transition_notif()
            MDIconButton:
                id: nav_icon5
                icon: 'account-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.84, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.transition_profile()
<Service_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Услуги'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'center_x': 0.03, 'center_y': 0.5}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "service_list"
                app.root.transition.direction = "right"
        MDIconButton:
            icon: 'star-outline'
            pos_hint: {'center_x': 0.96, 'center_y': 0.5}
            user_font_size: dp(24)
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2000
            canvas.after:
                Color:
                    rgba: (0,0,0,0.5)
                Line:
                    points: self.x, self.y+self.height*0.82, self.x+self.width, self.y+self.height*0.82
            Image:
                id: service_image
                size_hint: 0.4,0.4
                pos_hint: {'center_x': 0.5, 'center_y': 0.95}
                source: 'Image\\service_card.png'
            Label:
                id: name_service
                pos_hint: {'center_x': 0.205, 'center_y': 0.88}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Фамилия/Name'
            Label:
                id: date_service
                pos_hint: {'center_x': 0.205, 'center_y': 0.88}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Дата'
                opacity: 0
            Label:
                id: address_service
                pos_hint: {'center_x': 0.3, 'center_y': 0.86}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Адрес'
            Label:
                id: kind_service
                pos_hint: {'center_x': 0.21, 'center_y': 0.84}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Вид объявления'
            Label:
                id: type_price
                pos_hint: {'center_x': 0.245, 'center_y': 0.8}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Стоимость за сутки:'
            Label:
                id: price_service
                pos_hint: {'center_x': 0.45, 'center_y': 0.8}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Стоимость'
            Label:
                pos_hint: {'center_x': 0.245, 'center_y': 0.78}
                color: 0,0,0,1
                font_size: '18sp'
                text:'С кем работаю:'
            Label:
                id: kind_pet_serv
                pos_hint: {'center_x': 0.45, 'center_y': 0.78}
                size_hint: 0.4, None
                text_size: self.width, None
                color: 0,0,0,1
                font_size: '18sp'
                text:'со всеми'
            Label:
                id: size_dog1_serv
                pos_hint: {'center_x': 0.245, 'center_y': 0.75}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Размер собаки:'
                disabled: False
            Label:
                id: size_dog2_serv
                pos_hint: {'center_x': 0.45, 'center_y': 0.75}
                color: 0,0,0,1
                font_size: '18sp'
                size_hint: 0.4, None
                text_size: self.width, None
                text:'маленькие и средние породы'
                disabled: False
            Label:
                pos_hint: {'center_x': 0.245, 'center_y': 0.7}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Возраст:'
            Label:
                id: age_serv
                pos_hint: {'center_x': 0.45, 'center_y': 0.7}
                color: 0,0,0,1
                size_hint: 0.4, None
                text_size: self.width, None
                font_size: '18sp'
                text:'любой'
            Label:
                pos_hint: {'center_x': 0.2, 'center_y': 0.68}
                color: 0,0,0,1
                font_size: '18sp'
                text:'Специальные возможности:'
            Label:
                id: medicine
                pos_hint: {'center_x': 0.14, 'center_y': 0.66}
                color: 0,0,0,1
                font_size: '17sp'
                text:'- Давать лекарства'
                disabled: False
            Label:
                id: injection
                pos_hint: {'center_x': 0.13, 'center_y': 0.64}
                color: 0,0,0,1
                font_size: '17sp'
                text:'- Делать уколы'
                disabled: False
            Label:
                id: control
                pos_hint: {'center_x': 0.18, 'center_y': 0.62}
                color: 0,0,0,1
                font_size: '17sp'
                text:'- Круглосуточный контроль'
                disabled: False
            Label:
                id: education
                pos_hint: {'center_x': 0.245, 'center_y': 0.6}
                color: 0,0,0,1
                font_size: '17sp'
                text:'- Профильное образование'
                disabled: False
            Label:
                id: name_education
                pos_hint: {'center_x': 0.45, 'center_y': 0.6}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Ветеринар'
                disabled: False
            Label:
                pos_hint: {'center_x': 0.245, 'center_y': 0.58}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Контактный телефон:'
            Label:
                id: phone_serv
                pos_hint: {'center_x': 0.46, 'center_y': 0.58}
                color: 0,0,0,1
                size_hint: 0.4, None
                text_size: self.width, None
                font_size: '18sp'
                text:'89209048314'
            Label:
                pos_hint: {'center_x': 0.245, 'center_y': 0.56}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Комментарий'
            Label:
                id: comment
                color: 0,0,0,1
                font_size: '15sp'
                size_hint: 0.95, None
                text_size: self.width, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text:'Доброго времени суток. Помогите пожалуйста найти домашнего питомца. Был утерян в Белоозёрском Воскресенский район. В районе церкви. Убежал. Кобель американского стафордширского терьера. Зовут Дин. Ошейник красного цвета и адресник с номером телефона хозяина. Пожалуйста кто-то что-то видел или слышал сообщите. Будем благодарны за любую информацию'
            MDFillRoundFlatIconButton:
                id: btn_rev
                icon: "comment-outline"
                text: "Открыть отзывы"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
                theme_icon_color: "Custom"
                icon_color: 1, 1, 1, 1
                md_bg_color: 0.34,0.71,0.98,1
                font_size: '17sp'
                user_font_size: dp(36)
                pos_hint: {'center_x':0.5,'y':0.03}
                on_press:
                    app.root.current = 'review'  

<Profile_Screen>:
    on_enter: root.download_data()
    FloatLayout:
        size_hint: 1,0.93
        pos_hint: {'x':0,'y':0.07}
        canvas.before:
            Color:
                rgba: (1,0.71,0.98,1)
            Rectangle:
                pos: self.x, self.y + self.height*0.75
                size: self.width, self.height*0.25 
                source: 'Image\\image836.png'
        Image:
            id: avatar
            source: 'Image\\def_img_profile.png'
            size_hint: 0.2,0.2
            pos_hint: {'x':0.4,'y':0.65}
        Label:
            id: name_profile
            pos_hint: {'x':-0.08,'y':0.15}
            color: 0,0,0,1
            font_size: '25sp'
            text:'Артём'
        Label:
            id: lname_profile
            pos_hint: {'x':0.08,'y':0.15}
            color: 0,0,0,1
            font_size: '25sp'
            text:'Хорев'
        MDRectangleFlatButton:
            text: 'Личные данные'
            theme_text_color: 'Custom'
            text_color: 0, 0, 0, 1
            line_color: 0, 0, 0, 1
            size_hint: 1,None
            anchor_x: 'left'
            padding: [dp(16),dp(0)]
            font_size: '17sp'
            pos_hint: {'x':0,'y':0.49}
            on_release:
                app.root.current = 'data_personal'
        MDRectangleFlatButton:
            text: 'Мои объявления'
            theme_text_color: 'Custom'
            text_color: 0, 0, 0, 1
            line_color: 0, 0, 0, 1
            size_hint: 1,None
            anchor_x: 'left'
            padding: [dp(16),dp(0)]
            font_size: '17sp'
            pos_hint: {'x':0,'y':0.42}
            on_release:
                root.download_my_ad()
                app.root.current = 'my_ad'
        MDRectangleFlatButton:
            text: 'Мои услуги'
            theme_text_color: 'Custom'
            text_color: 0, 0, 0, 1
            line_color: 0, 0, 0, 1
            size_hint: 1,None
            anchor_x: 'left'
            padding: [dp(16),dp(0)]
            font_size: '17sp'
            pos_hint: {'x':0,'y':0.35}
            on_release:
                root.download_my_service()
                app.root.current = 'my_service'
        # MDRectangleFlatButton:
        #     text: 'Выбранные услуги'
        #     theme_text_color: 'Custom'
        #     text_color: 0, 0, 0, 1
        #     line_color: 0, 0, 0, 1
        #     size_hint: 1,None
        #     anchor_x: 'left'
        #     padding: [dp(16),dp(0)]
        #     font_size: '17sp'
        #     pos_hint: {'x':0,'y':0.32}
        # MDRectangleFlatButton:
        #     theme_text_color: 'Custom'
        #     text_color: 0, 0, 0, 1
        #     line_color: 0, 0, 0, 1
        #     text: 'Выбранные объявления'
        #     size_hint: 1,None
        #     anchor_x: 'left'
        #     padding: [dp(16),dp(0)]
        #     font_size: '17sp'
        #     pos_hint: {'x':0,'y':0.25}
        MDRectangleFlatButton:
            text: 'О приложении'
            theme_text_color: 'Custom'
            text_color: 0, 0, 0, 1
            line_color: 0, 0, 0, 1
            size_hint: 1,None
            anchor_x: 'left'
            padding: [dp(16),dp(0)]
            font_size: '17sp'
            #pos_hint: {'x':0,'y':0.18}
            pos_hint: {'x':0,'y':0.28}
        MDRectangleFlatIconButton:
            icon: "exit-to-app"
            text: "Выйти из аккаунта"
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 1
            line_color: 1, 1, 1, 1
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1
            pos_hint: {'x':0.65,'y':0.01}
            on_press:
                app.root.current = 'start'
            #pos_hint: {'x':0.65,'y':0.01}
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        md_bg_color: 1,1,1,1
        MDFloatLayout:
            canvas:
                Color:
                    rgba: (0,0,0,0.5)
                Line:
                    points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
            size_hint_x: 1
            pos_hint: {'x': 0, 'y': 0}
            MDIconButton:
                id: nav_icon1
                icon: 'paw'
                ripple_scale: 0.8
                pos_hint: {'x': 0.05, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0.34,0.71,0.98,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'main'
                    app.root.transition.direction = "right"
            MDIconButton:
                id: nav_icon2
                icon: 'clipboard-check-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.25, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'service_list'
                    app.root.transition.direction = "right"
            MDIconButton:
                id: nav_icon3
                icon: 'plus-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.45, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.current = 'add'
            MDIconButton:
                id: nav_icon4
                icon: 'bell-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.65, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.root.transition.direction = "right"
                    app.transition_notif()
            MDIconButton:
                id: nav_icon5
                icon: 'account-circle-outline'
                ripple_scale: 0.8
                pos_hint: {'x': 0.84, 'y': 0.1}
                user_font_size: dp(36)
                theme_text_color: 'Custom'
                text_color: 0,0,0,1
                on_release:
                    app.change_color(self)
                    app.transition_profile()
<Change_Password_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Смена пароля'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "data_personal"
                app.root.transition.direction = "right"
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.9
        pos_hint: {'x': 0.05, 'y': 0.6}
        spacing: '10dp'
        MDTextField:
            id: old_pass
            hint_text: "Старый пароль"
            mode: "line"
            password: True
            password_mask: '•'
        MDTextField:
            id: new_pass
            hint_text: "Новый пароль"
            mode: "line"
            password: True
            password_mask: '•'
            set_text: root.check_pass
        MDTextField:
            id: repeat_new_pass
            hint_text: "Повторите пароль"
            mode: "line"
            password: True
            password_mask: '•'
    MDIconButton:
        icon: 'eye-off'
        pos_hint: {'x': 0.9, 'y': 0.762}
        user_font_size: dp(24)
        on_release: root.ids.old_pass.password = False if root.ids.old_pass.password else True
        on_release: self.icon = 'eye' if root.ids.old_pass.password else 'eye-off'
    MDIconButton:
        icon: 'eye-off'
        pos_hint: {'x': 0.9, 'y': 0.681}
        user_font_size: dp(24)
        on_release: root.ids.new_pass.password = False if root.ids.new_pass.password else True
        on_release: self.icon = 'eye' if root.ids.new_pass.password else 'eye-off'
    MDIconButton:
        icon: 'eye-off'
        pos_hint: {'x': 0.9, 'y': 0.601}
        user_font_size: dp(24)
        on_release: root.ids.repeat_new_pass.password = False if root.ids.repeat_new_pass.password else True
        on_release: self.icon = 'eye' if root.ids.repeat_new_pass.password else 'eye-off'
    Label:
        id: pas_mes
        font_size: '14sp'
        color: 1,0,0,1
        text: 'Пароли не совпадают'
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: error_pass
        font_size: '11sp'
        color: 1,0,0,1
        text: 'Пароль не соответствует требованиям'
        pos_hint: {'center_x': 0.19, 'center_y': 0.68}
        size_hint_y: 0.01
        disabled: True
    Label:
        id: requirements_pass
        font_size: '11sp'
        color: 0,0,0,1
        text: 'Пароль должен содержать:\n- хотя бы одно число\n- хотя бы одну латинскую букву в нижнем и верхнем регистре\n- может содержать @#$%-_.\n- длина составляет от 6 до 20 символов'
        pos_hint: {'center_x': 0.34, 'center_y': 0.52}
        disabled: False
    RoundedButton:
        id: btn_save
        pos_hint: {'center_x': 0.5, 'center_y': 0.05}
        size_hint: 0.6, 0.05
        font_size: '20sp'
        color: 0,0,0,1
        text: root.change
        on_press: root.check_field()
<My_Ad_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Мои объявления'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_press:
                app.root.transition.direction = "right"             
                app.root.current = 'profile'  
    BoxLayout:
        orientation: "vertical"
        size_hint: 1,0.95
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            bar_color: [0, 0, 0, 1]
            MDBoxLayout:
                id: container_lost
                orientation: "vertical"
                adaptive_height: True
                spacing: dp(25)
<My_Service_Screen>:  
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Мои услуги'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "profile"
                app.root.transition.direction = "right"
    BoxLayout:
        orientation: "vertical"
        size_hint: 1,0.95
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            bar_color: [0, 0, 0, 1]
            MDBoxLayout:
                id: container_service
                orientation: "vertical"
                adaptive_height: True
                spacing: dp(25)   
<Personal_Data>:
    on_enter: root.download_data()
    FloatLayout:
        size_hint: 1,1
        pos_hint: {'x':0,'y':0}
        canvas.before:
            Color:
                rgba: (1,0.71,0.98,1)
            Rectangle:
                pos: self.x, self.y + self.height*0.75
                size: self.width, self.height*0.25 
                source: 'Image\\image836.png'
        MDIconButton:
            id: profile_icon
            icon: 'Image\\def_img_profile.png'
            user_font_size: '110sp'
            #size_hint: 0.2,0.2
            pos_hint: {'center_x':0.5,'y':0.65}
            on_press: root.download_image()
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.9
            pos_hint: {'x': 0.05, 'y': 0.25}
            spacing: '10dp'
            MDTextField:
                id: name_pd
                text: 'Name'
                color_mode: 'custom'
                text_color: 0,0,0,1
                mode: "line"
            MDTextField:
                id: lname_pd
                text: 'Lname'
                text_color: 0,0,0,1
                mode: "line"
            # MDTextField:
            #     id: city_pd
            #     text: 'Муром'
            #     text_color: 0,0,0,1
            #     mode: "line"
            MDTextField:
                id: email_pd
                text: 'Email'
                text_color: 0,0,0,1
                mode: "line"
            MDTextField:
                id: phone_pd
                text: 'Phone number'
                text_color: 0,0,0,1
                mode: "line"
        RoundedButton:
            pos_hint: {'x': 0.04, 'y': 0.16}
            size_hint: 0.11, 0.05
            font_size: '15sp'   
            text: 'Назад'
            on_release:
                app.root.transition.direction = "right" 
                app.root.current = 'profile'
        RoundedButton:
            pos_hint: {'x': 0.68, 'y': 0.16}
            size_hint: 0.28, 0.05
            font_size: '15sp'   
            text: root.change
            on_release:
                app.root.transition.direction = "left" 
                app.root.current = 'change_password'
        RoundedButton:
            pos_hint: {'x': 0.22, 'y': 0.02}
            size_hint: 0.6, 0.05
            font_size: '20sp'
            color: 0,0,0,1
            text: 'Сохранить'
            on_release:
                root.save_change()
                app.root.transition.direction = "right" 
                app.root.current = 'profile'
<Add_see_card>:
    size_hint: 0.7,0.05
    BoxLayout:
        Image:
            source: 'Image\\see_add.png'
            size_hint: 0.7, 0.7
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        BoxLayout:
            orientation: 'vertical'
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Нашел питомца'
<Add_lost_card>:
    size_hint: 0.7,0.05
    BoxLayout:
        Image:
            source: 'Image\\lost_add.png'
            size_hint: 0.7,0.7
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        BoxLayout:
            orientation: 'vertical'
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Потерял питомца'
<Add_overexposure_card>:
    size_hint: 0.7,0.05
    BoxLayout:
        Image:
            source: 'Image\\overexposure_add.png'
            size_hint: 0.7,0.7
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        BoxLayout:
            orientation: 'vertical'
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                size_hint_x: 0.8
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                text_size: self.width, None
                valign: 'middle'
                text:'Передержка животного'
<Add_nanny_card>:
    size_hint: 0.7,0.05
    BoxLayout:
        Image:
            source: 'Image\\nanny_add.png'
            size_hint: 0.7,0.7
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        BoxLayout:
            orientation: 'vertical'
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Няня'
<Add_walk_card>:
    size_hint: 0.7,0.05
    BoxLayout:
        Image:
            source: 'Image\\walk_add.png'
            size_hint: 0.7,0.7
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        BoxLayout:
            orientation: 'vertical'
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Выгул'
<Add_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Добавить'
    BoxLayout:
        orientation: 'vertical'
        size_hint: 0.7,0.85
        pos_hint: {'center_x': 0.61, 'center_y': 0.5}
        spacing: dp(10)
        Add_see_card:
            ripple_behavior: True
            line_color: (0,0,0,0.5)
            md_bg_color: (0.34,0.71,0.98,1)
            style: 'outlined'
            ripple_color: (0.34,0.71,0.98,0.1)
            on_press: app.root.current = 'add_see'
        Add_lost_card:
            id: add_lost_card
            ripple_behavior: True
            line_color: (0,0,0,0.5)
            md_bg_color: (0.34,0.71,0.98,1)
            style: 'outlined'
            ripple_color: (0.34,0.71,0.98,0.1)
            on_press: app.root.current = 'add_lost'
        Add_overexposure_card:
            id: add_overexposure_card
            ripple_behavior: True
            line_color: (0,0,0,0.5)
            md_bg_color: (0.34,0.71,0.98,1)
            style: 'outlined'
            ripple_color: (0.34,0.71,0.98,0.1)
            on_press: app.root.current = 'add_overexposure'
        Add_nanny_card:
            id: add_nanny_card
            ripple_behavior: True
            line_color: (0,0,0,0.5)
            md_bg_color: (0.34,0.71,0.98,1)
            style: 'outlined'
            ripple_color: (0.34,0.71,0.98,0.1)
            on_press: app.root.current = 'add_nanny'
        Add_walk_card:
            id: add_walk_card
            ripple_behavior: True
            line_color: (0,0,0,0.5)
            md_bg_color: (0.34,0.71,0.98,1)
            style: 'outlined'
            ripple_color: (0.34,0.71,0.98,0.1)
            on_press: app.root.current = 'add_walk'
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        md_bg_color: 1,1,1,1
        canvas:
            Color:
                rgba: (0,0,0,0.5)
            Line:
                points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
    MDIconButton:
        id: nav_icon1
        icon: 'paw'
        ripple_scale: 0.8
        pos_hint: {'x': 0.05, 'y': 0.01}
        user_font_size: sp(36)
        theme_text_color: 'Custom'
        text_color: 0.34,0.71,0.98,1
        on_release:
            #app.root.transition = NoTransition()
            app.change_color(self)
            app.root.current = 'main'
            app.root.transition.direction = "right"
    MDIconButton:
        id: nav_icon2
        icon: 'clipboard-check-outline'
        ripple_scale: 0.8
        pos_hint: {'x': 0.25, 'y': 0.01}
        user_font_size: dp(36)
        theme_text_color: 'Custom'
        text_color: 0,0,0,1
        on_release:
            app.change_color(self)
            app.root.current = 'service_list'
            app.root.transition.direction = "right"
    MDIconButton:
        id: nav_icon3
        icon: 'plus-circle-outline'
        ripple_scale: 0.8
        pos_hint: {'x': 0.45, 'y': 0.01}
        user_font_size: dp(36)
        theme_text_color: 'Custom'
        text_color: 0,0,0,1
        on_release:
            app.change_color(self)
            app.root.current = 'add'
    MDIconButton:
        id: nav_icon4
        icon: 'bell-outline'
        ripple_scale: 0.8
        pos_hint: {'x': 0.65, 'y': 0.01}
        user_font_size: dp(36)
        theme_text_color: 'Custom'
        text_color: 0,0,0,1
        on_release:
            app.change_color(self)
            app.transition_notif()
            app.root.transition.direction = "left"
    MDIconButton:
        id: nav_icon5
        icon: 'account-circle-outline'
        ripple_scale: 0.8
        pos_hint: {'x': 0.84, 'y': 0.01}
        user_font_size: dp(36)
        theme_text_color: 'Custom'
        text_color: 0,0,0,1
        on_release:
            app.change_color(self)
            app.transition_profile()
            app.root.transition.direction = "left"
<FileChooser>:
    id: filechooser
    BoxLayout:
        size: root.width,root.height
        orientation: 'vertical'
        FileChooserIconView:
            id: chooser
            #rootpath: '/storage/emulated/0/DCIM'
            on_selection: filechooser.selected(chooser.selection)
<Add_See_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Нашел'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "add"
                app.root.transition.direction = "right"
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2000
            MDLabel:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Вид'
                pos_hint: {'x': 0.08, 'y': 0.47}
            CheckBox:
                group: 'kind'
                id: kind_pet_cat
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.93}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Кошка'
                pos_hint: {'x': 0.22, 'y': 0.445}
            CheckBox:
                id: kind_pet_dog
                group: 'kind'
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.88}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Собака'
                pos_hint: {'x': 0.22, 'y': 0.395}
            MDLabel:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Пол'
                pos_hint: {'x': 0.08, 'y': 0.365}
            CheckBox:
                group: 'gender'
                id: gender_man
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.82}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Мальчик'
                pos_hint: {'x': 0.22, 'y': 0.335}
            CheckBox:
                group: 'gender'
                id: gender_wom
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.77}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Девочка'
                pos_hint: {'x': 0.22, 'y': 0.285}
            CheckBox:
                group: 'gender'
                id: gender_unk
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.72}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Неизвестно'
                pos_hint: {'x': 0.22, 'y': 0.235}
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Где видели'
                pos_hint: {'x': 0.08, 'y': 0.2}
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Контакты для связи'
                pos_hint: {'x': 0.08, 'y': 0.1}
            MDTextField:
                id: address
                hint_text: 'Адрес'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.65}
            Button:
                text: 'Определить местоположение'
                size_hint: 0.34,0.02
                background_color: 0,0,0,0.3
                color: 0,0,0,1
                pos_hint: {'x': 0.08, 'y': 0.62}
                on_press: root.gps_locate()
            MDLabel:
                pos_hint: {'x': 0.08, 'y': -0.04}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Фото'
            Button:
                text: 'Загрузить фото'
                size_hint: 0.2,0.02
                background_color: 0,0,0,0.3
                color: 0,0,0,1
                pos_hint: {'x': 0.08, 'y': 0.4}
                on_press: root.download_image()
            MDLabel:
                id: img
                pos_hint: {'x': 0.08, 'y': 0.6}
                color: 0,0,0,1
                font_size: '12sp'
                opacity: 0
            Label:
                id: path_img
                pos_hint: {'center_x': 0.3, 'center_y': 0.36}
                color: 0,0,0,1
                font_size: '12sp'
                opacity: 0
            MDTextField:
                id: name
                hint_text: 'Name'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.55}
            MDTextField:
                id: phone
                hint_text: 'Телефон'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.5}
            MDLabel:
                pos_hint: {'x': 0.08, 'y': -0.15}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Комментарий'
            MDTextFieldRect:
                id: comment
                multiline: True
                size_hint: 0.7, None
                pos_hint: {'x': 0.08, 'y': 0.22}
            RoundedButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.02}
                size_hint: 0.96, 0.02
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Добавить'
                on_release: root.add_see()
<Add_Lost_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Потерял'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "add"
                app.root.transition.direction = "right"
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2000
            MDLabel:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Вид'
                pos_hint: {'x': 0.08, 'y': 0.47}
            CheckBox:
                id: kind_pet_cat
                group: 'kind'
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.93}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Кошка'
                pos_hint: {'x': 0.22, 'y': 0.445}
            CheckBox:
                id: kind_pet_dog
                group: 'kind'
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.88}
                color: 0,0,0,1
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Собака'
                pos_hint: {'x': 0.22, 'y': 0.395}
            MDLabel:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Пол'
                pos_hint: {'x': 0.08, 'y': 0.365}
            CheckBox:
                id: gender_man
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.82}
                color: 0,0,0,1
                group: 'gender'
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Мальчик'
                pos_hint: {'x': 0.22, 'y': 0.335}
            CheckBox:
                id: gender_wom
                color: 0,0,0,1
                size_hint: None, None
                size: "60dp", "60dp"
                pos_hint: {'x': 0.05, 'y': 0.77}
                group: 'gender'
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Девочка'
                pos_hint: {'x': 0.22, 'y': 0.285}
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Где видели последний раз'
                pos_hint: {'x': 0.08, 'y': 0.25}
            MDTextField:
                id: address
                hint_text: 'Адрес'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.7}
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Кличка'
                pos_hint: {'x': 0.08, 'y': 0.17}
            MDTextField:
                id: nackname
                hint_text: 'Кличка'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.62}
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Контакты для связи'
                pos_hint: {'x': 0.08, 'y': 0.09}
            MDTextField:
                id: name
                hint_text: 'Name'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.55}
            MDTextField:
                id: phone
                hint_text: 'Телефон'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'x': 0.09, 'y': 0.5}
            MDLabel:
                pos_hint: {'x': 0.08, 'y': -0.1}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Фото'
            Button:
                text: 'Загрузить фото'
                size_hint: 0.2,0.02
                background_color: 0,0,0,0.3
                color: 0,0,0,1
                pos_hint: {'x': 0.08, 'y': 0.32}
                on_press: root.download_image()
            MDLabel:
                id: img
                pos_hint: {'x': 0.08, 'y': -0.14}
                color: 0,0,0,1
                font_size: '12sp'
                opacity: 0
            Label:
                id: path_img
                pos_hint: {'center_x': 0.3, 'center_y': 0.36}
                color: 0,0,0,1
                font_size: '12sp'
                opacity: 1
            MDLabel:
                pos_hint: {'x': 0.08, 'y': -0.25}
                color: 0,0,0,1
                font_size: '17sp'
                text:'Комментарий'
            MDTextFieldRect:
                id: comment
                multiline: True
                size_hint: 0.7, None
                pos_hint: {'x': 0.08, 'y': 0.15}
                
            RoundedButton:
                pos_hint: {'x': 0.011, 'y': 0.01}
                size_hint: 0.96, 0.02
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Добавить'
                on_release: root.apply_filter()
<Add_Overexposure_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Передержка'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "add"
                app.root.transition.direction = "right"
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2500
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Личные данные'
                pos_hint: {'center_x': 0.2, 'center_y': 0.98}
            MDTextField:
                id: fname
                hint_text: 'Name'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.95}
            MDTextField:
                id: lname
                hint_text: 'Фвмилия'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.92}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'С кем работаю'
                pos_hint: {'center_x': 0.18, 'center_y': 0.9}
            CheckBox:
                id: kind_cb_cat
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.87}
                color: 0,0,0,1
                on_active: root.active_cat()
                on_active: root.active_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Кошка'
                pos_hint: {'center_x': 0.2, 'center_y': 0.87}
            CheckBox:
                id: kind_cb_dog
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.84}
                color: 0,0,0,1
                on_active: root.active_dog()
                on_active: root.active_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Собака'
                pos_hint: {'center_x': 0.2, 'center_y': 0.84}
            CheckBox:
                id: kind_cb_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.81}
                color: 0,0,0,1
                on_active: root.active_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Со всеми'
                pos_hint: {'center_x': 0.2, 'center_y': 0.81}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Размер собаки'
                pos_hint: {'center_x': 0.18, 'center_y': 0.79}
            CheckBox:
                id: size_small
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.77}
                color: 0,0,0,1
                on_active: root.active_size_small()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Маленькие породы собак (до 12 кг и до 28 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.77}
            CheckBox:
                id: size_medium
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.74}
                color: 0,0,0,1
                on_active: root.active_size_medium()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Средние породы собак (12-25 кг, 28-60 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.74}
            CheckBox:
                id: size_large
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.71}
                color: 0,0,0,1
                on_active: root.active_size_large()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Крупные породы собак (от 25 кг, от 60 см рост)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.71}
            CheckBox:
                id: size_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.68}
                color: 0,0,0,1
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Любой'
                pos_hint: {'center_x': 0.65, 'center_y': 0.68}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Возраст'
                pos_hint: {'center_x': 0.12, 'center_y': 0.66}
            CheckBox:
                id: age_from_1
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.64}
                color: 0,0,0,1
                on_active: root.active_age_from_1()
                on_active: root.active_age_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'До 1 года'
                pos_hint: {'center_x': 0.3, 'center_y': 0.64}
            CheckBox:
                id: age_up_1
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.61}
                color: 0,0,0,1
                on_active: root.active_age_up_1()
                on_active: root.active_age_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Старше 1 года'
                pos_hint: {'center_x': 0.3, 'center_y': 0.61}
            CheckBox:
                id: age_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.58}
                color: 0,0,0,1
                on_active: root.active_age_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Любой'
                pos_hint: {'center_x': 0.3, 'center_y': 0.58}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Специальные возможности'
                pos_hint: {'center_x': 0.25, 'center_y': 0.55}
            MDSwitch:
                id: medicine
                pos_hint: {'center_x': 0.1, 'center_y': 0.53}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Давать лекарства'
                pos_hint: {'center_x': 0.5, 'center_y': 0.53}
            MDSwitch:
                id: injection
                pos_hint: {'center_x': 0.1, 'center_y': 0.51}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Делать уколы'
                pos_hint: {'center_x': 0.5, 'center_y': 0.51}
            MDSwitch:
                id: control
                pos_hint: {'center_x': 0.1, 'center_y': 0.49}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Круглосуточный контроль'
                pos_hint: {'center_x': 0.5, 'center_y': 0.49}
            MDSwitch:
                id: education
                pos_hint: {'center_x': 0.1, 'center_y': 0.47}
                width: dp(50)
                on_release: root.press_education()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Профильное образование'
                pos_hint: {'center_x': 0.5, 'center_y': 0.47}
            MDTextField:
                id: name_educ
                hint_text: 'Образование'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.45}
                opacity: 0
            MDTextField:
                id: phone
                hint_text: 'Телефон'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.43}
            MDTextField:
                id: address
                hint_text: 'Адрес'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            Button:
                text: 'Определить местоположение'
                size_hint: 0.42,0.015
                background_color: 0,0,0,0.3
                font_size: '15sp'
                color: 0,0,0,1
                pos_hint: {'center_x': 0.26, 'center_y': 0.38}
                on_press: root.gps_locate()
            Button:
                text: 'Загрузить фото'
                size_hint: 0.31,0.015
                background_color: 0,0,0,0.3
                font_size: '15sp'
                color: 0,0,0,1
                pos_hint: {'center_x': 0.21, 'center_y': 0.33}
                on_press: root.download_image()
            Label:
                color: 0,0,0,1
                font_size: '17sp'
                text:'Фото'
                pos_hint: {'center_x': 0.1, 'center_y': 0.36}
            Label:
                id: img
                pos_hint: {'center_x': 0.45, 'center_y': 0.33}
                color: 0,0,0,1
                font_size: '12sp'
                opacity: 0
            Label:
                id: path_img
                pos_hint: {'center_x': 0.3, 'center_y': 0.36}
                color: 0,0,0,1
                font_size: '12sp'
                opacity: 1
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'О себе'
                pos_hint: {'center_x': 0.1, 'center_y': 0.3}
            MDTextFieldRect:
                id: comment
                multiline: True
                size_hint: 0.85, None
                hint_text: 'Комментарий поможет продвинуть ваше объявление'
                pos_hint: {'center_x': 0.5, 'center_y': 0.26}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Стоимость за сутки'
                pos_hint: {'center_x': 0.13, 'center_y': 0.22}
            MDTextField:
                id: price
                size_hint_x: 0.85
                hint_text: 'Стоимость'
                pos_hint: {'center_x': 0.5, 'center_y': 0.2}
            RoundedButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.02}
                size_hint: 0.96, 0.02
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Применить'
                on_release: root.add()
<Add_Nanny_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Няня'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "add"
                app.root.transition.direction = "right"
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2500
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Личные данные'
                pos_hint: {'center_x': 0.2, 'center_y': 0.98}
            MDTextField:
                id: fname
                hint_text: 'Name'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.95}
            MDTextField:
                id: lname
                hint_text: 'Фвмилия'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.92}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'С кем работаю'
                pos_hint: {'center_x': 0.18, 'center_y': 0.9}
            CheckBox:
                id: kind_cb_cat
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.87}
                color: 0,0,0,1
                on_active: root.active_cat()
                on_active: root.active_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Кошка'
                pos_hint: {'center_x': 0.2, 'center_y': 0.87}
            CheckBox:
                id: kind_cb_dog
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.84}
                color: 0,0,0,1
                on_active: root.active_dog()
                on_active: root.active_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Собака'
                pos_hint: {'center_x': 0.2, 'center_y': 0.84}
            CheckBox:
                id: kind_cb_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.81}
                color: 0,0,0,1
                on_active: root.active_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Со всеми'
                pos_hint: {'center_x': 0.2, 'center_y': 0.81}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Размер собаки'
                pos_hint: {'center_x': 0.18, 'center_y': 0.79}
            CheckBox:
                id: size_small
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.77}
                color: 0,0,0,1
                on_active: root.active_size_small()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Маленькие породы собак (до 12 кг и до 28 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.77}
            CheckBox:
                id: size_medium
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.74}
                color: 0,0,0,1
                on_active: root.active_size_medium()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Средние породы собак (12-25 кг, 28-60 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.74}
            CheckBox:
                id: size_large
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.71}
                color: 0,0,0,1
                on_active: root.active_size_large()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Крупные породы собак (от 25 кг, от 60 см рост)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.71}
            CheckBox:
                id: size_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.68}
                color: 0,0,0,1
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Любой'
                pos_hint: {'center_x': 0.65, 'center_y': 0.68}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Возраст'
                pos_hint: {'center_x': 0.12, 'center_y': 0.66}
            CheckBox:
                id: age_from_1
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.64}
                color: 0,0,0,1
                on_active: root.active_age_from_1()
                on_active: root.active_age_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'До 1 года'
                pos_hint: {'center_x': 0.3, 'center_y': 0.64}
            CheckBox:
                id: age_up_1
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.61}
                color: 0,0,0,1
                on_active: root.active_age_up_1()
                on_active: root.active_age_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Старше 1 года'
                pos_hint: {'center_x': 0.3, 'center_y': 0.61}
            CheckBox:
                id: age_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.58}
                color: 0,0,0,1
                on_active: root.active_age_all()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Любой'
                pos_hint: {'center_x': 0.3, 'center_y': 0.58}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Специальные возможности'
                pos_hint: {'center_x': 0.3, 'center_y': 0.55}
            MDSwitch:
                id: medicine
                pos_hint: {'center_x': 0.1, 'center_y': 0.53}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Давать лекарства'
                pos_hint: {'center_x': 0.5, 'center_y': 0.53}
            MDSwitch:
                id: injection
                pos_hint: {'center_x': 0.1, 'center_y': 0.51}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Делать уколы'
                pos_hint: {'center_x': 0.5, 'center_y': 0.51}
            MDSwitch:
                id: control
                pos_hint: {'center_x': 0.1, 'center_y': 0.49}
                width: dp(50)
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Круглосуточный контроль'
                pos_hint: {'center_x': 0.5, 'center_y': 0.49}
            MDSwitch:
                id: education
                pos_hint: {'center_x': 0.1, 'center_y': 0.47}
                width: dp(50)
                on_release: root.press_education()
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Профильное образование'
                pos_hint: {'center_x': 0.5, 'center_y': 0.47}
            MDTextField:
                id: name_educ
                hint_text: 'Образование'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.45}
                opacity: 0
            MDTextField:
                id: phone
                hint_text: 'Телефон'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.43}
            MDTextField:
                id: address
                hint_text: 'Адрес'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'О себе'
                pos_hint: {'center_x': 0.1, 'center_y': 0.38}
            MDTextFieldRect:
                id: comment
                multiline: True
                size_hint: 0.85, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.35}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Стоимость за сутки'
                pos_hint: {'center_x': 0.12, 'center_y': 0.32}
            MDTextField:
                id: price
                size_hint_x: 0.85
                hint_text: 'Стоимость'
                pos_hint: {'center_x': 0.5, 'center_y': 0.29}
            RoundedButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.02}
                size_hint: 0.96, 0.02
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Применить'
                on_release: root.add()
<Add_Walk_Screen>:
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Выгул'
        MDIconButton:
            icon: 'arrow-left'
            pos_hint: {'x': 0, 'y': -0.1}
            user_font_size: dp(24)
            on_release:             
                app.root.current = "add"
                app.root.transition.direction = "right"
    ScrollView:
        id: scc
        do_scroll_x: False
        bar_color: [0, 0, 0, 1]
        size_hint: 1, 0.95
        FloatLayout:
            size_hint_y: None
            height: 2500
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Личные данные'
                pos_hint: {'center_x': 0.2, 'center_y': 0.98}
            MDTextField:
                id: fname
                hint_text: 'Name'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.95}
            MDTextField:
                id: lname
                hint_text: 'Фвмилия'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.92}
            Label:
                color: 0,0,0,1
                font_size: '20sp'
                text:'Размер собаки'
                pos_hint: {'center_x': 0.18, 'center_y': 0.9}
            CheckBox:
                id: size_small
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.85}
                color: 0,0,0,1
                on_active: root.active_size_small()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Маленькие породы собак (до 12 кг и до 28 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.85}
            CheckBox:
                id: size_medium
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.83}
                color: 0,0,0,1
                on_active: root.active_size_medium()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Средние породы собак (12-25 кг, 28-60 см роста)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.83}
            CheckBox:
                id: size_large
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.81}
                color: 0,0,0,1
                on_active: root.active_size_large()
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Крупные породы собак (от 25 кг, от 60 см рост)'
                pos_hint: {'center_x': 0.65, 'center_y': 0.81}
            CheckBox:
                id: size_all
                size_hint: None, None
                size: dp(60), dp(60)
                pos_hint: {'center_x': 0.1, 'center_y': 0.79}
                color: 0,0,0,1
                on_active: root.active_size_all()
            MDLabel:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Любой'
                pos_hint: {'center_x': 0.65, 'center_y': 0.79}
            MDTextField:
                id: phone
                hint_text: 'Телефон'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.75}
            MDTextField:
                id: address
                hint_text: 'Адрес'
                mode: 'line'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.72}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'О себе'
                pos_hint: {'center_x': 0.1, 'center_y': 0.68}
            MDTextFieldRect:
                id: comment
                multiline: True
                size_hint: 0.85, None
                pos_hint: {'center_x': 0.5, 'center_y': 0.65}
            Label:
                color: 0,0,0,1
                font_size: '18sp'
                text:'Стоимость за 30 минут прогулки'
                pos_hint: {'center_x': 0.25, 'center_y': 0.6}
            MDTextField:
                id: price
                hint_text: 'Стоимость'
                size_hint_x: 0.85
                pos_hint: {'center_x': 0.5, 'center_y': 0.56}
            RoundedButton:
                pos_hint: {'center_x': 0.5, 'center_y': 0.02}
                size_hint: 0.96, 0.02
                font_size: '20sp'
                color: 0,0,0,1
                text: 'Применить'
                on_release: root.add()
<Notification_Card>:
    size_hint_y: None
    height: 100
    size_hint_x: None
    width: 400
    orientation: 'vertical'
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    FloatLayout:
        size_hint: 1,1
        Label:
            id: textt
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Появился новый комментарий'
        Label:
            id: date
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            color: 0,0,0,1
            font_size: '18sp'
            text:'дата'
            opacity: 0
<Notification_Screen>:
    on_enter: root.notification()
    FloatLayout:
        size_hint: 1,0.05
        pos_hint: {'x':0,'y':0.95}
        canvas.before:
            Color:
                rgba: (0.34,0.71,0.98,1)
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'Уведомления'
        Label:
            id: count_com
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'0'
            opacity: 0
        Label:
            id: count_rev
            pos_hint: {'x':0,'y':0}
            color: 0,0,0,1
            font_size: '18sp'
            text:'0'
            opacity: 0
    GridLayout:
        id: container
        cols: 1
        size_hint: 0.7,0.88
        pos_hint: {'center_x':0.6,'y':0.07}
        spacing:dp(10)
    NavigationBar:
        size_hint: 1,0.07
        pos_hint: {'x': 0, 'y': 0}
        #elevation: 20
        md_bg_color: 1,1,1,1
        canvas:
            Color:
                rgba: (0,0,0,0.5)
            Line:
                points: self.x, self.y+self.height, self.x+self.width, self.y+self.height
        #MDFloatLayout:

        MDIconButton:
            id: nav_icon1
            icon: 'paw'
            ripple_scale: 0.8
            pos_hint: {'x': 0.05, 'y': 0.01}
            user_font_size: sp(36)
            theme_text_color: 'Custom'
            text_color: 0.34,0.71,0.98,1
            on_release:
                #app.root.transition = NoTransition()
                app.change_color(self)
                app.root.current = 'main'
        MDIconButton:
            id: nav_icon2
            icon: 'clipboard-check-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.25, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.root.current = 'service_list'
        MDIconButton:
            id: nav_icon3
            icon: 'plus-circle-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.45, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.root.current = 'add'
        MDIconButton:
            id: nav_icon4
            icon: 'bell-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.65, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.transition_notif()
        MDIconButton:
            id: nav_icon5
            icon: 'account-circle-outline'
            ripple_scale: 0.8
            pos_hint: {'x': 0.84, 'y': 0.01}
            user_font_size: dp(36)
            theme_text_color: 'Custom'
            text_color: 0,0,0,1
            on_release:
                app.change_color(self)
                app.transition_profile()
