-- MySQL Script generated by MySQL Workbench
-- Wed May 25 03:16:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pets` DEFAULT CHARACTER SET utf8 ;
USE `pets` ;

-- -----------------------------------------------------
-- Table `pets`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`City` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Profile` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `AVATAR` MEDIUMBLOB NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `CITY` INT NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `PHONE_NUMBER` INT NOT NULL,
  `SALT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Profile_Citys_idx` (`CITY` ASC),
  CONSTRAINT `fk_Profile_City`
    FOREIGN KEY (`CITY`)
    REFERENCES `pets`.`City` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Type_ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Type_ad` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Kind_Pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Kind_Pet` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Ad` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` INT NOT NULL,
  `KIND_PETS` INT NOT NULL,
  `GENDER` VARCHAR(45) NOT NULL,
  `PHOTO` MEDIUMBLOB NOT NULL,
  `LAT` FLOAT NOT NULL,
  `LON` FLOAT NOT NULL,
  `FIRST_NAME` VARCHAR(45) NULL,
  `PHONE_NUMBER` INT NULL,
  `TEXT` TEXT(60) NULL,
  `ID_PROFILE` INT NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Ad_Type_ad1_idx` (`TYPE` ASC),
  INDEX `fk_Ad_Kind_Pets_idx` (`KIND_PETS` ASC),
  CONSTRAINT `fk_Ad_Type_ad1`
    FOREIGN KEY (`TYPE`)
    REFERENCES `pets`.`Type_ad` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ad_Kind_Pets`
    FOREIGN KEY (`KIND_PETS`)
    REFERENCES `pets`.`Kind_Pet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Comment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PROFILE` INT NOT NULL,
  `ID_AD` INT NOT NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  `TEXT` TEXT(60) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Ad_idx` (`ID_AD` ASC),
  INDEX `fk_Profile_idx` (`ID_PROFILE` ASC),
  CONSTRAINT `fk_Comment_Ad`
    FOREIGN KEY (`ID_AD`)
    REFERENCES `pets`.`Ad` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Profile`
    FOREIGN KEY (`ID_PROFILE`)
    REFERENCES `pets`.`Profile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Type_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Type_Service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Kind_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Kind_Service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TYPE` INT NOT NULL,
  `KIND` INT NOT NULL,
  `ID_PROFILE` INT NOT NULL,
  `KIND_PETS` INT NOT NULL,
  `SIZE_DOG` VARCHAR(45) NULL,
  `AGE` VARCHAR(45) NOT NULL,
  `MEDICINE` TINYINT(1) NOT NULL,
  `INJECTION` TINYINT(1) NOT NULL,
  `CONTROL` TINYINT(1) NOT NULL,
  `EDUCATION` TINYINT(1) NOT NULL,
  `NAME_EDUCATION` VARCHAR(45) NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  `ADDRESS` VARCHAR(45) NOT NULL,
  `ABOUT_ME` TEXT(60) NULL,
  `PRICE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Type_idx` (`TYPE` ASC),
  INDEX `fk_Kind_idx` (`KIND` ASC),
  INDEX `fk_Profile_idx` (`ID_PROFILE` ASC),
  INDEX `fk_Service_Kind_pet_idx` (`KIND_PETS` ASC),
  CONSTRAINT `fk_Service_Type`
    FOREIGN KEY (`TYPE`)
    REFERENCES `pets`.`Type_Service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Kind`
    FOREIGN KEY (`KIND`)
    REFERENCES `pets`.`Kind_Service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Profile`
    FOREIGN KEY (`ID_PROFILE`)
    REFERENCES `pets`.`Profile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Kind_pet`
    FOREIGN KEY (`KIND_PETS`)
    REFERENCES `pets`.`Kind_Pet` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Review` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PROFILE` INT NOT NULL,
  `OD_SERVICE` INT NOT NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  `TEXT` TEXT(60) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Service_idx` (`OD_SERVICE` ASC),
  INDEX `fk_Profile_idx` (`ID_PROFILE` ASC),
  CONSTRAINT `fk_Review_Service`
    FOREIGN KEY (`OD_SERVICE`)
    REFERENCES `pets`.`Service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_Profile`
    FOREIGN KEY (`ID_PROFILE`)
    REFERENCES `pets`.`Profile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Favorite_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Favorite_Service` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PROFILE` INT NOT NULL,
  `ID_SERVICE` INT NOT NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Service_idx` (`ID_SERVICE` ASC),
  INDEX `fk_Profile_idx` (`ID_PROFILE` ASC),
  CONSTRAINT `fk_Favorite_Service_Service`
    FOREIGN KEY (`ID_SERVICE`)
    REFERENCES `pets`.`Service` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite_Service_Profile`
    FOREIGN KEY (`ID_PROFILE`)
    REFERENCES `pets`.`Profile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`.`Favorite_Ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets`.`Favorite_Ad` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PROFILE` INT NOT NULL,
  `ID_AD` INT NOT NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Ad_idx` (`ID_AD` ASC),
  INDEX `fk_Profile_idx` (`ID_PROFILE` ASC),
  CONSTRAINT `fk_Favorite_Ad_Ad`
    FOREIGN KEY (`ID_AD`)
    REFERENCES `pets`.`Ad` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite_Ad_Profile`
    FOREIGN KEY (`ID_PROFILE`)
    REFERENCES `pets`.`Profile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
